addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "1.6.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"  % "3.5")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"       % "1.1.2-1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"       % "1.0.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.2.1")
