#!/usr/bin/env ruby

def exec(cmd)
  abort("Error encountered, aborting") unless system(cmd)
end

puts "CI=#{ENV['CI']}"
puts "TRAVIS_BRANCH=#{ENV['TRAVIS_BRANCH']}"
puts "TRAVIS_PULL_REQUEST=#{ENV['TRAVIS_PULL_REQUEST']}"
puts "PUBLISH=#{ENV['PUBLISH']}"
puts "SONATYPE_USER=xxxx" if ENV['SONATYPE_USER']
puts "SONATYPE_PASS=xxxx" if ENV['SONATYPE_PASS']
puts "PGP_PASS=xxxx" if ENV['PGP_PASS']
puts

unless ENV['CI'] == 'true'
  abort("ERROR: Not running on top of Travis, aborting!")
end

unless ENV['PUBLISH'] == 'true'
  puts "Publish is disabled"
  exit
end

branch = ENV['TRAVIS_BRANCH']
pr = ENV['TRAVIS_PULL_REQUEST']

unless branch =~ /^(\d+\.\d+\.\d+)$/ || (branch == "master" && ENV['TRAVIS_PULL_REQUEST'] == 'false')
  puts "Exiting. Only publishing on master or version tags when not part of a pull request."
  exit 0
end

# Forcing a change to the root directory, if not there already
Dir.chdir(File.absolute_path(File.join(File.dirname(__FILE__), "..")))

puts "---"
puts "Running 'git describe'"
exec("git describe")

puts "---"
puts "Running 'sbt version'"
exec("sbt version")

# Go, go, go
puts "---"
puts "Running 'sbt release'"
exec("sbt release")
