#!/usr/bin/env ruby

def exec(cmd)
  abort("Error encountered, aborting") unless system(cmd)
end

puts "CI=#{ENV['CI']}"
puts "TRAVIS_BRANCH=#{ENV['TRAVIS_BRANCH']}"
puts "TRAVIS_PULL_REQUEST=#{ENV['TRAVIS_PULL_REQUEST']}"
puts "PUBLISH=#{ENV['PUBLISH']}"
puts "SONATYPE_USER=xxxx" if ENV['SONATYPE_USER']
puts "SONATYPE_PASS=xxxx" if ENV['SONATYPE_PASS']
puts "PGP_PASS=xxxx" if ENV['PGP_PASS']
puts

unless ENV['CI'] == 'true'
  abort("ERROR: Not running on top of Travis, aborting!")
end

unless ENV['PUBLISH'] == 'true'
  puts "Publish is disabled"
  exit
end

branch = ENV['TRAVIS_BRANCH']

unless branch == "master" || branch =~ /^(\d+\.\d+\.\d+)$/
  puts "Only deploying for `master` branch and version tags. Exiting!"
  exit 0
end

# Forcing a change to the root directory, if not there already
Dir.chdir(File.absolute_path(File.join(File.dirname(__FILE__), "..")))

puts "Running 'sbt version'"
exec("sbt version")

# Go, go, go
puts "Running 'sbt release'"
exec("sbt release")
